// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddressInput struct {
	State        string `json:"state"`
	City         string `json:"city"`
	Neighborhood string `json:"neighborhood"`
	Street       string `json:"street"`
	Number       string `json:"number"`
	ZipCode      string `json:"zipCode"`
}

type Mutation struct {
}

type Query struct {
}

type UserInput struct {
	Name       string        `json:"name"`
	Email      string        `json:"email"`
	DocumentID string        `json:"documentID"`
	Address    *AddressInput `json:"address"`
}
